name: Deploy Main

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: true

# * Do not use ${{ secrets }} in the `env` section other than ACCOUNT_AWS_ROLE_ARN 
env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: ${{ secrets.ACCOUNT_AWS_ROLE_ARN }}
  CDK_ENV_STACK_NAME: Caryn-test-stack
  BUCKET_DEPLOY_ROLE_ARN: ""

# * Safer to use ${{ secrets }} below

jobs:
  deploy:
    name: Deploy to AWS
    permissions:
      id-token: write # for aws-actions/configure-aws-credentials
      contents: read # for actions/checkout
    runs-on: ubuntu-latest
    steps:
      ##
      # Setup
      ##
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: DeployRoleForGitHubSession
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout Code
        uses: actions/checkout@v4
      - run: npm install 
      - run: npm --workspace packages/cdk run cdk -- deploy --require-approval never
      - name: Fetch Deploy Role ARN
        id: fetch-role-arn
        run: |
          BUCKET_DEPLOY_ROLE_ARN=$(aws cloudformation describe-stacks --stack-name $CDK_ENV_STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='DestinationBucketDeployRoleArn'].OutputValue" --output text)
          echo "BUCKET_DEPLOY_ROLE_ARN=$BUCKET_DEPLOY_ROLE_ARN" >> $GITHUB_ENV
      - name: Assume New AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.BUCKET_DEPLOY_ROLE_ARN }}
          role-session-name: BucketDeployGitHubSession
          aws-region: ${{ env.AWS_REGION }} 
      - run: | 
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name Caryn-test-stack --query "Stacks[0].Outputs[?OutputKey=='DestinationBucketName'].OutputValue" --output text)
          echo $BUCKET_NAME
          aws s3 sync --delete ./dist s3://$BUCKET_NAME  
